services:
  task-manager-api:
    build:
      context: .
      dockerfile: ./src/TrelloClone.Api/Dockerfile
    container_name: task-manager-api
    restart: always
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - isc-network

  task-manager-client:
    build:
      context: .
      dockerfile: ./src/TrelloClone.Client/Dockerfile
    container_name: task-manager-client
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./config/appsettings.json:/usr/share/nginx/html/appsettings.json:ro
    networks:
      - isc-network

networks:
  isc-network:
    driver: bridge
